---

- name: Create Consul configuration directory
  file: >
    path={{ consul_config_dir }}
    owner=root
    group={{ consul_group }}
    mode=0750
    state=directory
  tags: consul

- name: Create Consul service file
  template: >
    src=consul.initd.conf.j2
    dest=/etc/init.d/{{ consul_service_name }}
    owner=root
    group=root
    mode=0755
  when: ansible_os_family == 'RedHat'
  notify: restart consul
  tags:
    - consul
    - consul-template

- name: upstart init script
  template:
    src: "consul.upstart.conf.j2"
    dest: /etc/init/consul.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
  notify: restart consul

- name: update /etc/{{ consul_sysconfig_dir }}/{{ consul_service_name }}
  template:
    src: sysconfig.j2
    dest: "/etc/{{ consul_sysconfig_dir }}/{{ consul_service_name }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart consul
  tags:
    - consul
    - consul-sysconfig
    - consul-template

- include: dnsmasq.yml
  when: consul_dnsmasq_enable
  tags: consul_dnsmasq

- include: iptables.yml
  when: consul_iptables_enable
  tags:
    - consul  
    - consul-iptables

- name: avoid restarting consul twice if any config change notified service
  meta: flush_handlers
