---

- name: Create Consul configuration directory
  file: >
    path={{ consul_config_dir }}
    owner=root
    group={{ consul_group }}
    mode=0750
    state=directory
  tags: consul

- name: Create SYSV init script
  template: >
    src=consul.initd.conf.j2
    dest=/etc/init.d/{{ consul_service_name }}
    owner=root
    group=root
    mode=0755
  when: ansible_os_family == 'RedHat'
  notify: restart consul
  tags:
    - consul
    - consul-template

- name: Create upstart script
  template:
    src: "consul.upstart.conf.j2"
    dest: /etc/init/consul.conf
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_os_family == 'Debian'
    - ansible_service_mgr == 'upstart'
  notify: restart consul

- name: Create systemd service
  template:
    src: "consul.systemd.j2"
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0755
  when: ansible_service_mgr == 'systemd'
  notify: restart consul

- include: dnsmasq.yml
  when: consul_dnsmasq_enable
  tags: consul_dnsmasq

- include: iptables.yml
  when: consul_iptables_enable
  tags:
    - consul
    - consul-iptables

- name: avoid restarting consul twice if any config change notified service
  meta: flush_handlers
