---
- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: ensure dnsmasq.d directory
  file:
    state: directory
    dest: /etc/dnsmasq.d

- name: configure dnsmasq for consul domain
  copy:
    content: "server=/consul/127.0.0.1#8600"
    dest: /etc/dnsmasq.d/10-consul
  notify: restart dnsmasq

- name: start dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes
