---
# tasks file for consul

- name: Create Consul group
  group: name={{ consul_group }} system=yes state=present
  tags: consul

- name: Create Consul user
  user: >
    name={{ consul_user }}
    shell=/bin/false
    createhome={{ consul_user_create_home }}
    home={{ consul_user_home if consul_user_create_home and consul_user_home is defined else omit }}
    group={{ consul_group }}
    system=yes
    state=present
  tags: consul

- name: Download Consul
  get_url: >
    url={{ consul_url }}
    dest={{ consul_download_dir }}/consul.zip
    sha256sum={{ consul_sha256sum }}
  tags: consul

- name: Unzip Consul to installation directory
  unarchive: >
    src={{ consul_download_dir }}/consul.zip
    dest={{ consul_install_dir }}
    copy=no
  tags: consul

- name: Create Consul configuration directory
  file: >
    path={{ consul_config_dir }}
    owner=root
    group=root
    mode=0755
    state=directory
  tags: consul

- name: Create Consul upstart configuration
  template: >
    src=consul.conf.j2
    dest=/etc/init/consul.conf
    owner=root
    group=root
    mode=0644
  notify: restart consul
  tags:
    - consul
    - consul-template

- name: Create Consul configuration file
  template: >
    src=consul.json.j2
    dest={{ consul_config_dir }}/consul.json
    owner=root
    group={{ consul_config_file_group }}
    mode={{ consul_config_file_mode }}
  notify: restart consul
  tags:
    - consul
    - consul-template

- name: Create Consul services configuration file
  template: >
    src=services.json.j2
    dest={{ consul_config_dir }}/services.json
    owner=root
    group=root
    mode=0644
  notify: reload consul
  tags: consul

- name: Create Consul checks configuration file
  template: >
    src=checks.json.j2
    dest={{ consul_config_dir }}/checks.json
    owner=root
    group=root
    mode=0644
  notify: reload consul
  tags: consul

- name: Create Consul watches configuration file
  template: >
    src=watches.json.j2
    dest={{ consul_config_dir }}/watches.json
    owner=root
    group=root
    mode=0644
  notify: reload consul
  tags: consul

- include: webui.yml
  when: consul_webui
  tags:
    - consul
    - consul-webui

- name: Ensure Consul service is started and enabled on boot
  service: name={{ consul_service_name }} state=started enabled=yes
  tags: consul
