---
# tasks file for consul

- include: user.yml
  when: consul_create_user
  tags: consul_user

- include: install.yml
  tags: consul_install

- include: install-cli.yml
  when: consul_install_consul_cli
  tags: consul_cli

- include: config.yml
  tags: consul_config

- include: webui.yml
  when: consul_webui
  tags:
    - consul
    - consul-webui

- include: iptables.yml
  when: consul_iptables_enable
  tags:
    - consul  
    - consul-iptables

- name: Ensure Consul service is started and enabled on boot
  service: name={{ consul_service_name }} state=started enabled=yes
  tags: consul
