---

- name: configure consul services
  copy:
    dest: '{{ consul_config_dir }}/service-{{ item.key }}.json'
    owner: root
    group: root
    mode: '0644'
    content: "{{ { 'service': { 'name': item.value.name|default(item.key) } | combine(item.value) } | to_nice_json }}"
  with_dict: "{{ consul_services }}"
  notify: reload consul

- name: configure consul bulk services
  copy:
    dest: "{{ consul_config_dir }}/services.json"
    owner: root
    group: root
    mode: '0644'
    content: "{{ { 'services': consul_services_bulk } | to_nice_json }}"
  notify: reload consul
